### ISSUE TITLE
cryptomatte for arnold 2.0.2.4

### ISSUE THREAD

**Issue by JinGuo2012** [anderslanglands/alShaders2#19]
Arnold core 5.0.1.5 can't use Cryptomattes?

**Comment by jonahfriedman** [comment]
Yes it can. The minimum version is 5.0.1, when they added AOV shaders, and it says that on the requirements. In older versions of MtoA you may have to set up the AOV shader manually.

**Comment by JinGuo2012** [comment]
thanks . the version 5.0.2.1 can use

**Comment by jonahfriedman** [comment]
5.0.1 or any version after. 5.0.1.x is fine, 5.0.2.x is fine.
