### ISSUE TITLE
Hard crash when using Crypto AOVs + Custom AOVs 

### ISSUE THREAD

**Issue by danbradham** [anderslanglands/alShaders2#20]
Hello! First, I wanted to say thank you for releasing and maintaining alShaders for all these years, and releasing alShaders2 after solidangle introduced their own uber shader. I really appreciate all the hard work you've put in, it's made life with Arnold much better!

Recently Arnold 5.1 came out and now I'm getting a hard crash every time I try to render a scene containing an enabled crypto AOV and one or more enabled custom AOVs.

Script Editor Output:
Error: signal caught: C0000005 -- access violation

Maya scene:
https://drive.google.com/file/d/1NhO4OGbSrYCP8mxoP1WIXIVo31FA0Im6/view?usp=sharing

Software Versions
- Arnold 5.1
- mtoa3.0.0.1
- alShaders2.0.0b2
- Maya2018 update 2
- Windows 7

**Comment by jonahfriedman** [comment]
Thanks for the repro and all the other info. This is fixed in 42fa9d7 and will be in the next release!

**Comment by danbradham** [comment]
Awesome!
