### ISSUE TITLE
Hard crash with aiShadowMatte shader

### ISSUE THREAD

**Issue by LichiMan** [anderslanglands/alShaders2#24]
Hi,

I've just found that Maya crashes when I active Cryptomattes AOVs in a scene where an object have an aiShadowMatte shader assigned.

I've attached a scene where this happens:
[crypto_crash_with_shadowMatte_shader.zip](https://github.com/anderslanglands/alShaders2/files/1907918/crypto_crash_with_shadowMatte_shader.zip)

Software Versions
- Arnold 5.1.0.0
- MtoA 3.0.0.1
- alShaders 2.0.0b2
- Maya2018 update 2
- Windows 7

BTW, thank you so much for doing Cryptomattes :)

**Comment by jonahfriedman** [comment]
Thanks for the repro and all the other info. This is fixed in 42fa9d7 and will be in the next release!

**Comment by LichiMan** [comment]
Thank you Jonah!

**Comment by LichiMan** [comment]
Sorry to bother you.
We're starting a project where we're using MtoA 3 and I wanted to ask you if there's a way to release something before beta3 with this bug fixed? Or you know if beta3 is going to be released soon?
Thank you.
