### ISSUE TITLE
2.0.0-beta3 does not work under softimage 2015

### ISSUE THREAD

**Issue by rachyid** [anderslanglands/alShaders2#34]
Hi
Cryptomatte 2.00-beta3 does not work with softimage 2015 SP2
**WARNING : 3070-SIConnectShaderToCnxPoint - Type mismatch between shader and connection point.**
no problem with 2.0.0b2

**Comment by jonahfriedman** [comment]
Interesting. How are you using it in Softimage, and with what version of SitoA? 

It requires Arnold 5.0.1, and is meant to be used as an AOV shader. AOV shaders not currently exposed in SitoA, as far as I know, so any use of it would have to be in a way that was not intended. 

However, I think it should still work. It is simply an RGBA shader now, which should still work in all contexts that, for example, the "utility" shader still works. What are you trying to plug it into?

**Comment by rachyid** [comment]
Hi
Yes I'm using it with Arnold-5.1.1.0.
I edited theses files: ArnoldMenu.js,  ArnoldShaderDef.js,
ArnoldScenePreferences.js
but like I sad the Cryptomatte 2.0.0b3 does not work! Only beta 2.
I also edited the cryptomatte.mtd

[node cryptomatte]
    soft.category STRING "AOV"
    soft.order STRING "BeginGroup Cryptomatte_Globals Cryptomatte
sidecar_manifests cryptomatte_depth strip_obj_namespaces
strip_mat_namespaces EndGroup "
    "BeginGroup Standard_Cryptomatte_AOVs aov_crypto_asset
aov_crypto_object aov_crypto_material EndGroup "
    "BeginGroup User_Defined_Cryptomattes  "
    "BeginGroup User_Cryptomatte0 user_crypto_aov_0 user_crypto_src_0
EndGroup "
    "BeginGroup User_Cryptomatte1 user_crypto_aov_1 user_crypto_src_1
EndGroup "
    "BeginGroup User_Cryptomatte2 user_crypto_aov_2 user_crypto_src_2
EndGroup "
    "BeginGroup User_Cryptomatte3 user_crypto_aov_3 user_crypto_src_3
EndGroup "
    "EndGroup"
    desc STRING "Cryptomatte AOV Shader"
    aov_shader BOOL TRUE
    c4d.classification STRING "texture"
    c4d.menu STRING "texture"
    maya.name STRING "cryptomatte"
    maya.classification STRING "utility/aov"
    maya.id INT 0x00116422
    houdini.icon STRING "VOP_shadinglayer"
    houdini.category STRING "AOV"
    houdini.help_url STRING "
http://www.anderslanglands.com/alshaders/cryptomatte.html"
    houdini.parm.folder.ROOT STRING "Cryptomatte Globals;4;Standard
Cryptomatte AOVs;3;User Defined Cryptomattes;12;"
    houdini.parm.heading.h0 STRING "User Cryptomatte 0"
    houdini.parm.heading.h1 STRING "User Cryptomatte 1"
    houdini.parm.heading.h2 STRING "User Cryptomatte 2"
    houdini.parm.heading.h3 STRING "User Cryptomatte 3"
    houdini.order STRING " ROOT"
    houdini.order2 STRING " sidecar_manifests cryptomatte_depth
strip_obj_namespaces strip_mat_namespaces"
    houdini.order3 STRING " aov_crypto_asset aov_crypto_object
aov_crypto_material"
    houdini.order4 STRING " h0 user_crypto_aov_0 user_crypto_src_0 h1
user_crypto_aov_1 user_crypto_src_1 h2 user_crypto_aov_2 user_crypto_src_2
h3 user_crypto_aov_3 user_crypto_src_3"


here are attached file for ArnoldMenu.js,  ArnoldShaderDef.js,
ArnoldScenePreferences.js

**Comment by rachyid** [comment]
here is the link for images
https://we.tl/i2mBODQfDj

**Comment by rachyid** [comment]
all the parameter are listed in cryptomatte matching 100% with Maya, I'm showing only the top, you can see it in the attached image (link preview post)
and here is for beta 2.0.0b3, same thing I'm Showing only the top
[node cryptomatte]
	soft.category STRING "AOV"
	soft.order STRING "BeginGroup Cryptomatte_Globals Cryptomatte sidecar_manifests cryptomatte_depth strip_obj_namespaces strip_mat_namespaces  EndGroup "
	"BeginGroup Standard_Cryptomatte_AOVs aov_crypto_asset aov_crypto_object aov_crypto_material EndGroup "	
	"BeginGroup Name_processing_Options "
    "BeginGroup _______ preview_in_exr process_paths process_obj_path_pipes process_maya process_mat_path_pipes process_legacy EndGroup "	
    "EndGroup "
	"BeginGroup User_Defined_Cryptomattes "	
	"BeginGroup User_Cryptomatte0 user_crypto_aov_0 user_crypto_src_0  EndGroup "
	"BeginGroup User_Cryptomatte1 user_crypto_aov_1 user_crypto_src_1  EndGroup "
	"BeginGroup User_Cryptomatte2 user_crypto_aov_2 user_crypto_src_2  EndGroup "	
	"BeginGroup User_Cryptomatte3 user_crypto_aov_3 user_crypto_src_3  EndGroup "	
    "EndGroup"
	desc STRING "Cryptomatte AOV Shader"
	aov_shader BOOL TRUE
	c4d.classification STRING "texture"
	c4d.menu STRING "texture"
	soft.category STRING "AOV"
	maya.name STRING "cryptomatte"

**Comment by rachyid** [comment]
No I'm not using SPDL
I put the mtd and the dll file into C:\Users\rachid\Autodesk\Softimage_2015_R2-SP2\Addons\SItoA\Application\Plugins\bin\nt-x86-64

**Comment by jonahfriedman** [comment]
OK, two things:

1. Cryptomatte is not a closure shader anymore as of Beta 3, and I strongly suspect that's what is causing your problems. Since your are creating your own shader definitions, you probably need to fix this somewhere and I don't know where, and sorry I can't support your code. The closure node in your screenshot should not be necessary. The Cryptomatte shader should behave like an RGBA shader (like utility) and not a closure shader (like standard surface), as I said before. 
2. You do not have all of the shader parameters in your .mtd file, there were new ones added in Beta 3 that you don't have, for example "process_paths". The [full list is here](https://github.com/anderslanglands/alShaders2/blob/master/cryptomatte/cryptomatte_shader.cpp#L33-L55), for reference. 

I hope that helps you with your code.

**Comment by jonahfriedman** [comment]
Glad to hear you worked it out. 

For operator nodes, I think that's probably a big project which involves adding features to the SitoA c++ code.

**Comment by rachyid** [comment]
Hope someone of the team are working on

**Comment by jonahfriedman** [comment]
SitoA is an open source project now, and you can see its progress over here:

**Comment by rachyid** [comment]
Yes, but no operator node, no contour filter, no noice
