### ISSUE TITLE
alShaders splitted into 2 repos?

### ISSUE THREAD

**Issue by kybin** [anderslanglands/alShaders2#37]
README says the repo is moved to Psyop/CryptomatteArnold, 
but it seems this repo still holds alShaders directory for maya. 

It's little confusing. Will it merged to Psyop/CryptomatteArnold?

**Comment by jonahfriedman** [comment]
This repo, AlShaders2, only ever contained Cryptomatte, as does the CryptomatteArnold repo. That project has moved. I think you are confusing it with the transition version of AlShaders, which is somewhere else, and there's no reason to use this repo anymore.
