### ISSUE TITLE
custom crypto are missing manifest - HtoA

### ISSUE THREAD

**Issue by martinkindl83** [anderslanglands/alShaders2#8]
When using custom crypto mattes (as the default ones are no use in HtoA) we have problems where manifests are empty, thus giving us raw IDs (numbers) inside Nuke. This worked fine in Arnold4, doenst work in Arnold5.

I can provide ass files, scenes and EXRs if needed. This is a big problem, currently holding us back to Arnold4.

**Comment by martinkindl83** [comment]
using overrides doesnt help as manifests are having wrong inside assigments - they disregard overrides and uses original strings

**Comment by jonahfriedman** [comment]
A bug with specifically custom cryptomatte manifests was fixed in the latest dev branch.
